#!/bin/bash

# Docker Machine

alias dm="docker-machine"
alias dmls="docker-machine ls"
alias dmup="docker-machine start"
alias dmdn="docker-machine stop"
dmenv () {
	eval $(docker-machine env)
	echo DOCKER_TLS_VERIFY = $DOCKER_TLS_VERIFY
	echo DOCKER_HOST = $DOCKER_HOST
	echo DOCKER_CERT_PATH = $DOCKER_CERT_PATH
	echo DOCKER_MACHINE_NAME = $DOCKER_MACHINE_NAME
}
