#!/bin/bash

# Docker Machine

alias dm="docker-machine"
alias dmls="docker-machine ls"
alias dmup="docker-machine start"
alias dmdn="docker-machine stop"

dmenv () {
	eval $(docker-machine env)
	echo DOCKER_TLS_VERIFY = $DOCKER_TLS_VERIFY
	echo DOCKER_HOST = $DOCKER_HOST
	echo DOCKER_CERT_PATH = $DOCKER_CERT_PATH
	echo DOCKER_MACHINE_NAME = $DOCKER_MACHINE_NAME
}

dmc (){
	echo "\nCreating default docker machine"
    echo "Enter number of machine CPUs: "
    read cpu
    if [ -z "$cpu" ]; then
    	echo "No value provided, defaulting to 4 CPUs"
		cpu=4
	fi
    echo "Enter maching memory (GB): "
    read mem
    if [ -z "$mem" ]; then
    	echo "No value provided, defaulting to 16GB"
		mem=16
	fi
    echo "Enter maching disk size (GB): "
    read size
    if [ -z "$size" ]; then
    	echo "No value provided, defaulting to 100GB"
		size=100
	fi
	memmb=$((mem*1024))
	sizemb=$((size*1024))
	echo "$memmb"
	echo "$sizemb"
	docker-machine rm default
	docker-machine create --driver virtualbox --virtualbox-cpu-count $cpu --virtualbox-memory $memmb --virtualbox-disk-size $sizemb default
	docker-machine stop default
	# echo "Enabling USB functionality on default..."
	# vboxmanage modifyvm default --usb on
	# vboxmanage usbfilter add 0 --target default --name <name> --vendorid <vid> --productid <pid>
	docker-machine start default
	eval $(docker-machine env default)
}
