#!/bin/bash

# Yubikey
export YUBIKEY_SSH_AUTH_SOCK='/usr/local/var/run/yubikey-agent.sock'

alias yk='ykman'
alias ykp='yubico-piv-tool'
alias yssh='export SSH_AUTH_SOCK=$YUBIKEY_SSH_AUTH_SOCK'
alias yk_get_piv='ssh-keygen -D /usr/local/lib/opensc-pkcs11.so'

yk_reset_piv () {
	# Yubico defaults
	dpin="123456"
	dpuk="12345678"
	dmk="010203040506070801020304050607080102030405060708"
	ykman piv reset
    ykman piv access change-management-key
    echo "Default PUK: $dpuk"
    ykman piv access change-puk
    echo "Default PIN: $dpin"
    ykman piv access change-pin
}

yk_set_piv() {
	echo "Generating keys and certificate..."
	o_folder=~/Desktop
	echo "Output files will be written to $o_folder"
	yubico-piv-tool -s 9a -a generate -k --pin-policy=once --touch-policy=always --algorithm=RSA2048 -o $o_folder/yubikey_public_key.pem
	yubico-piv-tool -a verify-pin -a selfsign-certificate -s 9a -S '/CN=piv/' --valid-days=365 -i $o_folder/yubikey_public_key.pem -o $o_folder/yubikey_certificate.pem
	yubico-piv-tool -k -a import-certificate -s 9a -i $o_folder/yubikey_certificate.pem
	ssh-keygen -D /usr/local/lib/opensc-pkcs11.so > $o_folder/yubikey_ssh_key.txt
}
